version: '3.3'

networks:
  app_net:
    driver: bridge

services:
  golang:
    depends_on:
      - db
    image: golang:1.19.1-alpine3.16
    container_name: goenv
    networks:
      - app_net
    working_dir: /aulas
    ports:
      - 5000:5000
    volumes:
      - /home/wiles/aulas-go/secao-7/go:/aulas
    command:  tail -f /dev/null
  db:
    image: mysql:5.7
    networks:
      - app_net
    ports:
      - 3306:3306
    volumes:
      - /home/wiles/aulas-go/secao-7/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: devbook
      MYSQL_USER: golang
      MYSQL_PASSWORD: golang
      MYSQL_ROOT_PASSWORD: admin